import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <ClerkProvider>
    <html lang="en">
    <body className={inter.className}>
      
      <SignedOut>
          {/* <SignInButton /> */}
        </SignedOut>
        
      <main className='bg-bgPrimary'>
        <Header />
        {children}
      <Footer />
      </main>
    </body>
  </html>
      </ClerkProvider>
  )
}
